### PR TITLE
Core lightning can be started

### PR DESCRIPTION
**Pull request by litch**
Initial passthrough of this

### CODE REVIEW

**Comment by litch** [comment]
So currently this can start and fund a CLN node. 

I can't open a channel to/from them yet, and it seems a bit awkward to try to build that functionality before just putting a trait for the nodes, since there is a fair amount to `lnds`, etc, here.

**Comment by tee8z** [comment]
I just merged in having all the LND logic behind a trait, there should be an easier path forward with this now. Thank you for posting a PR!

**Comment by tee8z** [comment]
I'm working to work off what you've done here to add support for core LN, it should be much easier now that we have eclair support merged in.

**Comment by tee8z** [comment]
closing as I was able to merge in a branch that built of this one, I gave you co-author on the commit: 
https://github.com/tee8z/doppler/pull/21

**Pull request closed without merging**
